version: "3"
services:
  mysql-docker:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rediswithspring
      MYSQL_USER: heeseung
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_PASSWORD: test1234
      container-name: "docker-mysql"

  redis-docker:
    image: redis:latest
    command: redis-server --port 6379
    container_name: "docker-redis"
    labels:
      - "name=reids"
      - "mode=standalone"
    ports:
      - "6379:6379"